//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { schema as $schema, type SchemaType as $Schema } from "./schema";
import { type ModelResult as $ModelResult } from "@zenstackhq/orm";
/**
 * Файл (изображения, шрифты и т.д.)
 */
export type File = $ModelResult<$Schema, "File">;
/**
 * Франшиза — группа связанных аниме
 * Определяется через REST API /api/animes/{id}/franchise
 * Все аниме в одном графе = одна франшиза
 */
export type Franchise = $ModelResult<$Schema, "Franchise">;
/**
 * Аниме-тайтл
 */
export type Anime = $ModelResult<$Schema, "Anime">;
/**
 * Жанр
 */
export type Genre = $ModelResult<$Schema, "Genre">;
/**
 * Связь жанров и аниме (many-to-many)
 */
export type GenreOnAnime = $ModelResult<$Schema, "GenreOnAnime">;
/**
 * Тема аниме (Жестокость, Городское фэнтези, Школа и т.д.)
 */
export type Theme = $ModelResult<$Schema, "Theme">;
export type ThemeOnAnime = $ModelResult<$Schema, "ThemeOnAnime">;
/**
 * Связь между двумя аниме (сиквел, приквел, спин-офф и т.д.)
 */
export type AnimeRelation = $ModelResult<$Schema, "AnimeRelation">;
/**
 * Сезон аниме (TV, OVA, Movie и т.д.)
 */
export type Season = $ModelResult<$Schema, "Season">;
/**
 * Аудиодорожка эпизода
 */
export type AudioTrack = $ModelResult<$Schema, "AudioTrack">;
/**
 * Субтитры эпизода
 */
export type SubtitleTrack = $ModelResult<$Schema, "SubtitleTrack">;
/**
 * Шрифт для ASS субтитров
 */
export type SubtitleFont = $ModelResult<$Schema, "SubtitleFont">;
/**
 * Глава эпизода (для навигации и автопропуска)
 */
export type Chapter = $ModelResult<$Schema, "Chapter">;
/**
 * Эпизод (серия)
 */
export type Episode = $ModelResult<$Schema, "Episode">;
/**
 * Прогресс просмотра
 */
export type WatchProgress = $ModelResult<$Schema, "WatchProgress">;
/**
 * Настройки приложения (singleton)
 */
export type Settings = $ModelResult<$Schema, "Settings">;
/**
 * Профиль кодирования
 */
export type EncodingProfile = $ModelResult<$Schema, "EncodingProfile">;
/**
 * Элемент очереди импорта
 * Хранит настройки из wizard'а для последовательной обработки
 */
export type ImportQueueItem = $ModelResult<$Schema, "ImportQueueItem">;
/**
 * Подписка на библиотеку другого пользователя (P2P Sharing)
 */
export type Subscription = $ModelResult<$Schema, "Subscription">;
/**
 * Удалённый трекер в федеративной сети
 */
export type Tracker = $ModelResult<$Schema, "Tracker">;
/**
 * Федеративный контент — импортированный из другого трекера
 */
export type FederatedContent = $ModelResult<$Schema, "FederatedContent">;
/**
 * Настройки федерации (singleton)
 */
export type FederationSettings = $ModelResult<$Schema, "FederationSettings">;
/**
 * Статистика пользователя (singleton)
 */
export type UserStats = $ModelResult<$Schema, "UserStats">;
/**
 * Дневная статистика
 */
export type DailyStats = $ModelResult<$Schema, "DailyStats">;
/**
 * Репутация пользователя (singleton)
 */
export type UserReputation = $ModelResult<$Schema, "UserReputation">;
/**
 * Разблокированное достижение пользователя
 */
export type UserAchievement = $ModelResult<$Schema, "UserAchievement">;
/**
 * Прогресс достижения
 */
export type AchievementProgress = $ModelResult<$Schema, "AchievementProgress">;
/**
 * Бонусные очки пользователя (singleton)
 */
export type UserBonusPoints = $ModelResult<$Schema, "UserBonusPoints">;
/**
 * Транзакция бонусных очков
 */
export type BonusTransaction = $ModelResult<$Schema, "BonusTransaction">;
/**
 * Профиль пользователя для P2P синхронизации (singleton)
 * Заменяет OrbitDB UserProfileDB — хранится в SQLite, публикуется через IPNS
 */
export type LocalUserProfile = $ModelResult<$Schema, "LocalUserProfile">;
/**
 * Друг в P2P сети
 * Хранит информацию о принятых друзьях для PresenceSync
 */
export type Friend = $ModelResult<$Schema, "Friend">;
/**
 * Запрос в друзья (входящий/исходящий)
 */
export type FriendRequest = $ModelResult<$Schema, "FriendRequest">;
export const AnimeStatus = $schema.enums.AnimeStatus.values;
export type AnimeStatus = (typeof AnimeStatus)[keyof typeof AnimeStatus];
/**
 * Первоисточник аниме
 */
export const AnimeSource = $schema.enums.AnimeSource.values;
/**
 * Первоисточник аниме
 */
export type AnimeSource = (typeof AnimeSource)[keyof typeof AnimeSource];
/**
 * Возрастной рейтинг
 */
export const AgeRating = $schema.enums.AgeRating.values;
/**
 * Возрастной рейтинг
 */
export type AgeRating = (typeof AgeRating)[keyof typeof AgeRating];
export const VideoCodec = $schema.enums.VideoCodec.values;
export type VideoCodec = (typeof VideoCodec)[keyof typeof VideoCodec];
/**
 * Предпочтения выбора дорожек при просмотре
 */
export const TrackPreference = $schema.enums.TrackPreference.values;
/**
 * Предпочтения выбора дорожек при просмотре
 */
export type TrackPreference = (typeof TrackPreference)[keyof typeof TrackPreference];
export const SeasonType = $schema.enums.SeasonType.values;
export type SeasonType = (typeof SeasonType)[keyof typeof SeasonType];
export const ChapterType = $schema.enums.ChapterType.values;
export type ChapterType = (typeof ChapterType)[keyof typeof ChapterType];
export const FileCategory = $schema.enums.FileCategory.values;
export type FileCategory = (typeof FileCategory)[keyof typeof FileCategory];
export const RateControl = $schema.enums.RateControl.values;
export type RateControl = (typeof RateControl)[keyof typeof RateControl];
export const Tune = $schema.enums.Tune.values;
export type Tune = (typeof Tune)[keyof typeof Tune];
export const Multipass = $schema.enums.Multipass.values;
export type Multipass = (typeof Multipass)[keyof typeof Multipass];
export const BRefMode = $schema.enums.BRefMode.values;
export type BRefMode = (typeof BRefMode)[keyof typeof BRefMode];
export const RelationKind = $schema.enums.RelationKind.values;
export type RelationKind = (typeof RelationKind)[keyof typeof RelationKind];
/**
 * Статус просмотра аниме (как на Shikimori)
 */
export const WatchStatus = $schema.enums.WatchStatus.values;
/**
 * Статус просмотра аниме (как на Shikimori)
 */
export type WatchStatus = (typeof WatchStatus)[keyof typeof WatchStatus];
/**
 * Статус элемента очереди импорта
 */
export const ImportQueueItemStatus = $schema.enums.ImportQueueItemStatus.values;
/**
 * Статус элемента очереди импорта
 */
export type ImportQueueItemStatus = (typeof ImportQueueItemStatus)[keyof typeof ImportQueueItemStatus];
/**
 * Уровень доверия к трекеру
 */
export const TrustLevel = $schema.enums.TrustLevel.values;
/**
 * Уровень доверия к трекеру
 */
export type TrustLevel = (typeof TrustLevel)[keyof typeof TrustLevel];
/**
 * Ранги пользователя (для репутации)
 */
export const UserRank = $schema.enums.UserRank.values;
/**
 * Ранги пользователя (для репутации)
 */
export type UserRank = (typeof UserRank)[keyof typeof UserRank];
/**
 * Тип транзакции бонусных очков
 */
export const BonusTransactionType = $schema.enums.BonusTransactionType.values;
/**
 * Тип транзакции бонусных очков
 */
export type BonusTransactionType = (typeof BonusTransactionType)[keyof typeof BonusTransactionType];
/**
 * Уровень достижения
 */
export const AchievementTier = $schema.enums.AchievementTier.values;
/**
 * Уровень достижения
 */
export type AchievementTier = (typeof AchievementTier)[keyof typeof AchievementTier];
