//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { schema as $schema, type SchemaType as $Schema } from "./schema";
import { type ModelResult as $ModelResult } from "@zenstackhq/orm";
/**
 * Файл (изображения, шрифты и т.д.)
 */
export type File = $ModelResult<$Schema, "File">;
/**
 * Франшиза — группа связанных аниме
 * Определяется через REST API /api/animes/{id}/franchise
 * Все аниме в одном графе = одна франшиза
 */
export type Franchise = $ModelResult<$Schema, "Franchise">;
/**
 * Аниме-тайтл
 */
export type Anime = $ModelResult<$Schema, "Anime">;
/**
 * Жанр
 */
export type Genre = $ModelResult<$Schema, "Genre">;
/**
 * Студия анимации
 */
export type Studio = $ModelResult<$Schema, "Studio">;
/**
 * Связь студий и аниме (many-to-many)
 */
export type StudioOnAnime = $ModelResult<$Schema, "StudioOnAnime">;
/**
 * Персона (режиссёр, сейю, аниматор и т.д.)
 */
export type Person = $ModelResult<$Schema, "Person">;
/**
 * Связь персон с аниме (режиссёры, сценаристы и т.д.)
 */
export type PersonOnAnime = $ModelResult<$Schema, "PersonOnAnime">;
/**
 * Персонаж аниме
 */
export type Character = $ModelResult<$Schema, "Character">;
/**
 * Связь персонажей с аниме
 */
export type CharacterOnAnime = $ModelResult<$Schema, "CharacterOnAnime">;
/**
 * Связь персонажа с сейю (кто озвучивает)
 */
export type CharacterVoice = $ModelResult<$Schema, "CharacterVoice">;
/**
 * Внешняя ссылка (MAL, AniDB, официальный сайт)
 */
export type ExternalLink = $ModelResult<$Schema, "ExternalLink">;
/**
 * Видео (трейлеры, опенинги, эндинги) — v0.5.3
 */
export type Video = $ModelResult<$Schema, "Video">;
/**
 * Команда озвучки (fandub)
 */
export type Fandubber = $ModelResult<$Schema, "Fandubber">;
/**
 * Связь команд озвучки с аниме
 */
export type FandubberOnAnime = $ModelResult<$Schema, "FandubberOnAnime">;
/**
 * Команда субтитров (fansub)
 */
export type Fansubber = $ModelResult<$Schema, "Fansubber">;
/**
 * Связь команд субтитров с аниме
 */
export type FansubberOnAnime = $ModelResult<$Schema, "FansubberOnAnime">;
/**
 * Связь жанров и аниме (many-to-many)
 */
export type GenreOnAnime = $ModelResult<$Schema, "GenreOnAnime">;
/**
 * Тема аниме (Жестокость, Городское фэнтези, Школа и т.д.)
 */
export type Theme = $ModelResult<$Schema, "Theme">;
export type ThemeOnAnime = $ModelResult<$Schema, "ThemeOnAnime">;
/**
 * Связь между двумя аниме (сиквел, приквел, спин-офф и т.д.)
 */
export type AnimeRelation = $ModelResult<$Schema, "AnimeRelation">;
/**
 * Сезон аниме (TV, OVA, Movie и т.д.)
 */
export type Season = $ModelResult<$Schema, "Season">;
/**
 * Аудиодорожка эпизода
 */
export type AudioTrack = $ModelResult<$Schema, "AudioTrack">;
/**
 * Субтитры эпизода
 */
export type SubtitleTrack = $ModelResult<$Schema, "SubtitleTrack">;
/**
 * Шрифт для ASS субтитров
 */
export type SubtitleFont = $ModelResult<$Schema, "SubtitleFont">;
/**
 * Глава эпизода (для навигации и автопропуска)
 */
export type Chapter = $ModelResult<$Schema, "Chapter">;
/**
 * Эпизод (серия)
 */
export type Episode = $ModelResult<$Schema, "Episode">;
/**
 * Прогресс просмотра
 */
export type WatchProgress = $ModelResult<$Schema, "WatchProgress">;
/**
 * Настройки приложения (singleton)
 */
export type Settings = $ModelResult<$Schema, "Settings">;
/**
 * Профиль кодирования
 */
export type EncodingProfile = $ModelResult<$Schema, "EncodingProfile">;
/**
 * Элемент очереди импорта
 * Хранит настройки из wizard'а для последовательной обработки
 */
export type ImportQueueItem = $ModelResult<$Schema, "ImportQueueItem">;
export const AnimeStatus = $schema.enums.AnimeStatus.values;
export type AnimeStatus = (typeof AnimeStatus)[keyof typeof AnimeStatus];
/**
 * Первоисточник аниме
 */
export const AnimeSource = $schema.enums.AnimeSource.values;
/**
 * Первоисточник аниме
 */
export type AnimeSource = (typeof AnimeSource)[keyof typeof AnimeSource];
/**
 * Возрастной рейтинг
 */
export const AgeRating = $schema.enums.AgeRating.values;
/**
 * Возрастной рейтинг
 */
export type AgeRating = (typeof AgeRating)[keyof typeof AgeRating];
export const TranscodeStatus = $schema.enums.TranscodeStatus.values;
export type TranscodeStatus = (typeof TranscodeStatus)[keyof typeof TranscodeStatus];
export const VideoCodec = $schema.enums.VideoCodec.values;
export type VideoCodec = (typeof VideoCodec)[keyof typeof VideoCodec];
/**
 * Предпочтения выбора дорожек при просмотре
 */
export const TrackPreference = $schema.enums.TrackPreference.values;
/**
 * Предпочтения выбора дорожек при просмотре
 */
export type TrackPreference = (typeof TrackPreference)[keyof typeof TrackPreference];
export const SeasonType = $schema.enums.SeasonType.values;
export type SeasonType = (typeof SeasonType)[keyof typeof SeasonType];
export const ChapterType = $schema.enums.ChapterType.values;
export type ChapterType = (typeof ChapterType)[keyof typeof ChapterType];
export const FileCategory = $schema.enums.FileCategory.values;
export type FileCategory = (typeof FileCategory)[keyof typeof FileCategory];
export const RateControl = $schema.enums.RateControl.values;
export type RateControl = (typeof RateControl)[keyof typeof RateControl];
export const Tune = $schema.enums.Tune.values;
export type Tune = (typeof Tune)[keyof typeof Tune];
export const Multipass = $schema.enums.Multipass.values;
export type Multipass = (typeof Multipass)[keyof typeof Multipass];
export const BRefMode = $schema.enums.BRefMode.values;
export type BRefMode = (typeof BRefMode)[keyof typeof BRefMode];
export const RelationKind = $schema.enums.RelationKind.values;
export type RelationKind = (typeof RelationKind)[keyof typeof RelationKind];
export const PersonRole = $schema.enums.PersonRole.values;
export type PersonRole = (typeof PersonRole)[keyof typeof PersonRole];
export const ExternalLinkKind = $schema.enums.ExternalLinkKind.values;
export type ExternalLinkKind = (typeof ExternalLinkKind)[keyof typeof ExternalLinkKind];
export const VideoKind = $schema.enums.VideoKind.values;
export type VideoKind = (typeof VideoKind)[keyof typeof VideoKind];
/**
 * Статус просмотра аниме (как на Shikimori)
 */
export const WatchStatus = $schema.enums.WatchStatus.values;
/**
 * Статус просмотра аниме (как на Shikimori)
 */
export type WatchStatus = (typeof WatchStatus)[keyof typeof WatchStatus];
/**
 * Статус элемента очереди импорта
 */
export const ImportQueueItemStatus = $schema.enums.ImportQueueItemStatus.values;
/**
 * Статус элемента очереди импорта
 */
export type ImportQueueItemStatus = (typeof ImportQueueItemStatus)[keyof typeof ImportQueueItemStatus];
